name: Exciting
domain_name: Exciting.io
url: http://exciting.io
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - public
  - feed.xml
gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-feed
assets:
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/vendors/bootstrap-sass/stylesheets
    - _assets/vendors/bootstrap-sass/javascripts
    - _assets/vendors/bootstrap-sass/fonts
