source 'https://rubygems.org'

gem 'jekyll'
gem 'kramdown'
# gem 'bootstrap-sass', git: 'https://github.com/thomas-mcdonald/bootstrap-sass.git', branch: '3'
gem 'sass'
gem 'jekyll-assets'
gem 'uglifier'
gem 'rake'
gem 'htmlentities'
